# Generated by Django 5.1.2 on 2024-10-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='funcionario',
        ),
    ]
