# Generated by Django 5.1.2 on 2024-10-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0004_alter_endereco_id'),
        ('funcionario', '0005_remove_funcionario_endereco'),
        ('secretaria', '0002_remove_secretaria_endereco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
