# Generated by Django 5.1.2 on 2024-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0005_delete_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=6)),
            ],
        ),
    ]
