# Generated by Django 5.1.2 on 2024-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processo', '0002_delete_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
