# Generated by Django 5.1.2 on 2024-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('processo', '0001_initial'),
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='processos',
            field=models.ManyToManyField(related_name='funcionario', to='processo.processo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='secretarias',
            field=models.ManyToManyField(related_name='funcionarios', to='secretaria.secretaria'),
        ),
    ]
