# Generated by Django 5.1.2 on 2024-10-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_processos_funcionario_secretarias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
    ]
