# Generated by Django 5.1.2 on 2024-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_remove_endereco_funcionario'),
        ('funcionario', '0003_remove_funcionario_nome'),
        ('processo', '0001_initial'),
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.ManyToManyField(related_name='enderecos_funcionario', to='endereco.endereco'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='processos',
            field=models.ManyToManyField(related_name='processos_funcionario', to='processo.processo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='secretarias',
            field=models.ManyToManyField(related_name='secretarias_funcionarios', to='secretaria.secretaria'),
        ),
    ]
