# Generated by Django 5.1.2 on 2024-10-19 16:13

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('endereco', '0006_initial'),
        ('funcionario', '0006_delete_funcionario'),
        ('processo', '0003_initial'),
        ('secretaria', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('data_nascimento', models.DateTimeField()),
                ('endereco', models.ManyToManyField(related_name='enderecos_funcionario', to='endereco.endereco')),
                ('processos', models.ManyToManyField(related_name='processos_funcionario', to='processo.processo')),
                ('secretarias', models.ManyToManyField(related_name='secretarias_funcionarios', to='secretaria.secretaria')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
