# Generated by Django 5.1.2 on 2024-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionario/'),
        ),
    ]
