# Generated by Django 5.1.2 on 2024-10-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='endereco',
        ),
    ]
